version: '3'

services:
  redis:
    image: redis:7.2.3
    container_name: RecLetterRedis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - recletter-network

  mariadb:
    image: mariadb:10.4
    container_name: RecLetterMariaDB
    ports:
      - "3306:3306"
    volumes:
      - mariadb-data:/lib/var/mysql
    environment:
      MARIADB_DATABASE: ${DB_NAME}
      MARIADB_USER: ${USER_NAME}
      MARIADB_PASSWORD: ${USER_PASSWORD}
      MARIADB_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
    networks:
      - recletter-network

  recletterBackend:
    image: ssuyas/recletter_backend
    container_name: RecLetterBackend
    ports:
      - "8081:8080"
    networks:
      - recletter-network

  recletterFrontend:
    image: ssuyas/recletter_frontend
    container_name: RecLetterFrontend
    ports:
      - "80:80"
    networks:
      - recletter-network
volumes:
  redis-data:
  mariadb-data:

networks:
  recletter-network:

