version: '3'

services:
  RecLetterRedis:
    image: redis:7.2.3
    container_name: RecLetterRedis
    volumes:
      - redis-data:/data
    networks:
      - RecLetterNetwork

  RecLetterMariaDB:
    image: mariadb:10.4
    container_name: RecLetterMariaDB
    volumes:
      - mariadb-data:/lib/var/mysql
      - ./initdb.d:/docker-entrypoint-initdb.d
    networks:
      - RecLetterNetwork
    environment:
      MARIADB_DATABASE: ${DB_NAME}
      MARIADB_USER: ${USER_NAME}
      MARIADB_PASSWORD: ${USER_PASSWORD}
      MARIADB_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
    env_file:
      - .env

volumes:
  redis-data:
  mariadb-data:

networks:
  RecLetterNetwork:
    external: true