version: '3.1'

services:

  openvidu-server:
    image: openvidu/openvidu-server:2.29.0
    restart: on-failure
    container_name: RecLetterOpenVidu
    network_mode: "RecLetterNetwork"
    entrypoint: ['/usr/local/bin/entrypoint.sh']
    volumes:
      - ../coturn:/run/secrets/coturn
      - /var/run/docker.sock:/var/run/docker.sock
      - ${OPENVIDU_RECORDING_PATH}:${OPENVIDU_RECORDING_PATH}
      - ${OPENVIDU_RECORDING_CUSTOM_LAYOUT}:${OPENVIDU_RECORDING_CUSTOM_LAYOUT}
      - ${OPENVIDU_CDR_PATH}:${OPENVIDU_CDR_PATH}
    env_file:
      - .env
    environment:
      - SERVER_SSL_ENABLED=false
      - SERVER_PORT=5443
      - KMS_URIS=["ws://RecLetterKurento:8888/kurento"]
      - COTURN_IP=${COTURN_IP:-auto-ipv4}
      - COTURN_PORT=${COTURN_PORT:-3478}
    logging:
      options:
        max-size: "${DOCKER_LOGS_MAX_SIZE:-100M}"

  kms:
    image: ${KMS_IMAGE:-kurento/kurento-media-server:7.0.1}
    restart: always
    container_name: RecLetterKurento
    network_mode: "RecLetterNetwork"
    ulimits:
      core: -1
    volumes:
      - /opt/openvidu/kms-crashes:/opt/openvidu/kms-crashes
      - ${OPENVIDU_RECORDING_PATH}:${OPENVIDU_RECORDING_PATH}
      - /opt/openvidu/kurento-logs:/opt/openvidu/kurento-logs
    environment:
      - KMS_MIN_PORT=40000
      - KMS_MAX_PORT=57000
      - GST_DEBUG=${KMS_DOCKER_ENV_GST_DEBUG:-}
      - KURENTO_LOG_FILE_SIZE=${KMS_DOCKER_ENV_KURENTO_LOG_FILE_SIZE:-100}
      - KURENTO_LOGS_PATH=/opt/openvidu/kurento-logs
    logging:
      options:
        max-size: "${DOCKER_LOGS_MAX_SIZE:-100M}"

  coturn:
    image: openvidu/openvidu-coturn:2.29.0
    restart: on-failure
    container_name: RecLetterCoturn
    network_mode: "RecLetterNetwork"
    ports:
      - "${COTURN_PORT:-3478}:${COTURN_PORT:-3478}/tcp"
      - "${COTURN_PORT:-3478}:${COTURN_PORT:-3478}/udp"
    env_file:
      - .env
    volumes:
      - ../coturn:/run/secrets/coturn
    command:
      - --log-file=stdout
      - --listening-port=${COTURN_PORT:-3478}
      - --fingerprint
      - --min-port=${COTURN_MIN_PORT:-57001}
      - --max-port=${COTURN_MAX_PORT:-65535}
      - --realm=openvidu
      - --verbose
      - --use-auth-secret
      - --static-auth-secret=$${COTURN_SHARED_SECRET_KEY}
    logging:
      options:
        max-size: "${DOCKER_LOGS_MAX_SIZE:-100M}"