version: '3'

services:
  RecLetterBackend:
    image: ssuyas/recletter_backend
    container_name: RecLetterBackend
    restart: unless-stopped
    network_mode: host
    ports:
      - "8081:8080"
    environment:
      DB_URL: ${DB_URL}
      USER_NAME: ${USER_NAME}
      USER_PASSWORD: ${USER_PASSWORD}
      MAIL_ID: ${MAIL_ID}
      MAIL_SECRET: ${MAIL_SECRET}
      AWS_ACCESS: ${AWS_ACCESS}
      AWS_SECRET: ${AWS_SECRET}
      OPENVIDU_URL: ${OPENVIDU_URL}
      OPENVIDU_SECRET: ${OPENVIDU_SECRET}
    env_file:
      - .env

  RecLetterFrontend:
    image: ssuyas/recletter_frontend
    container_name: RecLetterFrontend
    network_mode: host
    depends_on:
      - RecLetterBackend
