version: '3'

services:
  redis:
    image: redis:7.2.3
    container_name: RecLetterRedis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - recletter-network

  mariadb:
    image: mariadb:10.4
    container_name: RecLetterMariaDB
    ports:
      - "3306:3306"
    volumes:
      - mariadb-data:/lib/var/mysql
      - ../backend/db/initdb.d:/docker-entrypoint-initdb.d
    environment:
      MARIADB_DATABASE: ${DB_NAME}
      MARIADB_USER: ${USER_NAME}
      MARIADB_PASSWORD: ${USER_PASSWORD}
      MARIADB_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      TZ: Asia/Seoul
    networks:
      - recletter-network
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci

  zookeeper:
    image: wurstmeister/zookeeper:latest
    container_name: zookeeper
    ports:
      - "2181:2181"
  kafka:
    image: bitnami/kafka:3.6
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 127.0.0.1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
volumes:
  redis-data:
  mariadb-data:

networks:
  recletter-network:

