version: '3.1'

services:
  RecLetterBackend:
    image: ssuyas/recletter_backend
    container_name: RecLetterBackend
    restart: unless-stopped
    ports:
      - "8081:8081"
    networks:
      - RecLetterNetwork
    volumes:
      - ./private_cloudfront_key.pem:/private_cloudfront_key.pem
    environment:
      DB_URL: ${DB_URL}
      USER_NAME: ${USER_NAME}
      USER_PASSWORD: ${USER_PASSWORD}
      MAIL_ID: ${MAIL_ID}
      MAIL_SECRET: ${MAIL_SECRET}
      AWS_ACCESS: ${AWS_ACCESS}
      AWS_SECRET: ${AWS_SECRET}
      AWS_REGION: ${AWS_REGION}
      AWS_BUCKET: ${AWS_BUCKET}
      AWS_FRONT: ${AWS_FRONT}
      AWS_CLOUDFRONT_DOMAIN: ${AWS_CLOUDFRONT_DOMAIN}
      AWS_CLOUDFRONT_KEY: ${AWS_CLOUDFRONT_KEY}
      AWS_CLOUDFRONT_KEY_ID: ${AWS_CLOUDFRONT_KEY_ID}
      JWT_KEY: ${JWT_KEY}
      REDIS_HOST: ${REDIS_HOST}
      REDIS_PORT: ${REDIS_PORT}
      GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID}
      GOOGLE_CLIENT_SECRET: ${GOOGLE_CLIENT_SECRET}
      OPENVIDU_URL: ${OPENVIDU_URL}
      OPENVIDU_SECRET: ${OPENVIDU_SECRET}
    env_file:
      - .env

  app:
    image: ssuyas/recletter_frontend
    container_name: RecLetterFrontend
    network_mode: host
    depends_on:
      - RecLetterBackend
    command: sh -c echo "VITE_REACT_GOOGLE_LOGIN_URL=${VITE_REACT_GOOGLE_LOGIN_URL}" > /usr/share/nginx/html/.env && echo "VITE_REACT_GOOGLE_LOGIN_URL=${VITE_REACT_GOOGLE_LOGIN_URL}" > /usr/share/nginx/html/.env && echo "VITE_REACT_GOOGLE_CHANGE_HOST=${VITE_REACT_GOOGLE_CHANGE_HOST}" > /usr/share/nginx/html/.env && echo "VITE_REACT_GOOGLE_PROTOCOL=${VITE_REACT_GOOGLE_PROTOCOL}" > /usr/share/nginx/html/.env && echo "VITE_REACT_API_URL=${VITE_REACT_API_URL}" > /usr/share/nginx/html/.env
networks:
  RecLetterNetwork:
    external: true
