spring:
  messages:
    basename: errors, messages
    encoding: UTF-8
  config:
    import:
      - optional:file:.env[.properties]
  datasource:
    url: ${DB_URL}
#    hikari:
#      driver-class-name: org.mariadb.jdbc.Driver
#      jdbc-url: ${DB_URL}
#      username: ${USER_NAME}
#      password: ${USER_PASSWORD}
#      maximum-pool-size: 15
#      minimum-idle: 1
#      connection-timeout: 5000
#      connection-init-sql: SELECT 1
#      idle-timeout: 600000
#      max-lifetime: 1800000
#      auto-commit: true
    username: ${USER_NAME}
    password: ${USER_PASSWORD}
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        show_sql: true
        format_sql: true
        use_sql_comments: true
    database-platform: org.hibernate.dialect.MariaDB103Dialect
  data:
    redis:
      host: localhost
      port: 6379

access-token:
  private: access-refresh-token-keys/access-token-private.key
  public: access-refresh-token-keys/access-token-public.key

refresh-token:
  private: access-refresh-token-keys/refresh-token-private.key
  public: access-refresh-token-keys/refresh-token-public.key