spring:
  messages:
    basename: errors, messages
    encoding: UTF-8
  config:
    import:
      - optional:file:.env[.properties]
  datasource:
    url: ${DB_URL}
    username: ${USER_NAME}
    password: ${USER_PASSWORD}
    driver-class-name: org.mariadb.jdbc.Driver
  #    hikari:
  #      driver-class-name: org.mariadb.jdbc.Driver
  #      jdbc-url: ${DB_URL}
  #      username: ${USER_NAME}
  #      password: ${USER_PASSWORD}
  #      maximum-pool-size: 15
  #      minimum-idle: 1
  #      connection-timeout: 5000
  #      connection-init-sql: SELECT 1
  #      idle-timeout: 600000
  #      max-lifetime: 1800000
  #      auto-commit: true
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true
    database-platform: org.hibernate.dialect.MariaDBDialect
  data:
    redis:
      host: localhost
      port: 6379
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_ID}
    password: ${MAIL_SECRET}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000
    auth-code-expiration-millis: 600000  # 10분

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_ID}
    password: ${MAIL_SECRET}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000
    auth-code-expiration-millis: 600000  # 10분

cloud:
  aws:
    s3:
      bucket: sunjbucket
    region:
      static: ap-northeast-2
    stack:
      auto: false
    credentials:
      access-key: ${AWS_ACCESS}
      secret-key: ${AWS_SECRET}

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
    com:
      sixcube:
        recletter: debug
    "[org.springframework.security]": DEBUG

access-token:
  private: access-refresh-token-keys/access-token-private.key
  public: access-refresh-token-keys/access-token-public.key

refresh-token:
  private: access-refresh-token-keys/refresh-token-private.key
  public: access-refresh-token-keys/refresh-token-public.key

  openvidu:
    url: ${OPENVIDU_URL}
    secret: ${MY_SECRET}